### ISSUE TITLE
"Invalid response from kyoo" during initial registration

### ISSUE THREAD

**Issue by btxshark1** [AnonymusRaccoon/Kyoo#967]
### Kyoo's version

4.7

### What happened?

I'm having difficulties getting Kyoo deployed, hoping I missed something easy. 

How I got here:
- Pull compose and env from github
- Update library path 
- `docker compose up` 
- "No admin account has been created yet. Please register to create one." -> follow link to register
- "Invalid response from kyoo" trying to register

In the browser console:
![Image](https://github.com/user-attachments/assets/e1519106-d6a3-419b-8e9b-fd1c0aba729a)

The only non-library scan related output from the containers is 
`traefik-1      | 172.23.0.1 - - [28/May/2025:00:59:30 +0000] "POST /api/auth/register HTTP/1.1" 307 0 "-" "-" 68 "front@docker" "http://172.23.0.7:8901" 21ms
traefik-1      | 172.23.0.1 - - [28/May/2025:00:59:30 +0000] "POST /setup?step=MissingAdminAccount HTTP/1.1" 200 10564 "-" "-" 69 "front@docker" "http://172.23.0.7:8901" 113ms
`

I tried adding my OIDC to the .env and the option shows up on top of the login and registration forms but the link points back to itself without reaching out to the provider (goes from kyoo.domain.com to kyoo.domain.com without an auth.domain.com in the mix)
"Continue with Authelia" -> 
`https://kyoo.<my domain>.com/api/auth/login/authelia?redirectUrl=https://kyoo.<my domain>.com/login/callback`
but I'm not sure if thats because I need to have an admin account created first or something with my setup. 

![Image](https://github.com/user-attachments/assets/ff861af8-fe54-48b9-b853-db4ee0965ccf)

Anything to help point me in the right direction is greatly appreciated!

**Comment by zoriya** [comment]
Can you send logs of the `back` service please?

OIDC flow seems correct to me, you first reach kyoo's backend before being redirected to the identity provider (authentik)

**Comment by btxshark1** [comment]
I have made some changes to the compose

- I made a new network named `kyoo` and put everything on it (this seems the likely culprit)
- I added the images to my local harbor proxy cache because the internet here is very slow
- I moved the named volumes to `/opt/kyoo/<name>` to fit better into my backups

```
---
---
networks:
  kyoo:
    driver: bridge

x-transcoder: &transcoder-base
  image: harbor.domain.com/ghcr.io/zoriya/kyoo_transcoder:4.7
  networks:
    kyoo:
      aliases:
        - transcoder
  restart: unless-stopped
  env_file:
    - ./.env
  environment:
    - GOCODER_PREFIX=/video
  volumes:
    - /mnt/TV-Shows:/video/TV-Shows:ro
    - /mnt/Movies:/video/Movies:ro
    - ${CACHE_ROOT}:/cache
    - /opt/kyoo/metadata:/metadata       
       
services:          
  back:
    image: harbor.domain.com/ghcr.io/zoriya/kyoo_back:4.7        
    networks:      
      - kyoo       
    restart: unless-stopped    
    cpus: 1.5      
    environment:   
      - TRANSCODER_URL=${TRANSCODER_URL:-http://transcoder:7666/video}         
      - KYOO_PREFIX=/api       
    env_file:      
      - ./.env     
    depends_on:    
      postgres:    
        condition: service_healthy         
      meilisearch: 
        condition: service_healthy         
      rabbitmq:    
        condition: service_healthy         
      migrations:  
        condition: service_completed_successfully      
    volumes:       
      - /opt/kyoo/kyoo:/metadata           
    labels:        
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api/`)"
  front:
    image: harbor.domain.com/ghcr.io/zoriya/kyoo_front:4.7
    networks:
      - kyoo
    restart: unless-stopped
    environment:
      - KYOO_URL=${KYOO_URL:-http://back:5000/api}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=PathPrefix(`/`)"
  traefik:
    image: harbor.domain.com/hub.docker.com/traefik:v3.2
    networks:
      - kyoo
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:8901"
      - "--accesslog=true"
    ports:
      - "8901:8901"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

```
